In [1]:
import numpy as np

In [2]:
populasyon = np.random.randint(0,80,10000)

In [3]:
populasyon

array([16, 28, 64, ..., 16, 29, 28])

In [4]:
populasyon[0:10]

array([16, 28, 64, 68, 52, 57, 78, 19,  4, 71])

In [5]:
#Örneklem Çekimi

In [6]:
np.random.seed(115)
orneklem = np.random.choice(a=populasyon,size = 100)
orneklem[0:10]

array([77, 19, 56, 17, 37,  4, 70, 11, 59, 66])

In [7]:
orneklem.mean()

42.81

In [8]:
populasyon.mean()

39.5274

In [9]:
#orneklem dağılımı


In [10]:
np.random.seed(10)
orneklem1 = np.random.choice(a = populasyon, size = 100)
orneklem2 = np.random.choice(a = populasyon, size = 100)
orneklem3 = np.random.choice(a = populasyon, size = 100)
orneklem4 = np.random.choice(a = populasyon, size = 100)
orneklem5 = np.random.choice(a = populasyon, size = 100)
orneklem6 = np.random.choice(a = populasyon, size = 100)
orneklem7 = np.random.choice(a = populasyon, size = 100)
orneklem8 = np.random.choice(a = populasyon, size = 100)
orneklem9 = np.random.choice(a = populasyon, size = 100)
orneklem10 = np.random.choice(a = populasyon, size = 100)

In [11]:
(orneklem1.mean() + orneklem2.mean() + orneklem3.mean() + orneklem4.mean() + orneklem5.mean() 
+ orneklem6.mean() + orneklem7.mean() + orneklem8.mean() + orneklem9.mean() + orneklem10.mean() )  / 10

39.521

In [12]:
orneklem1.mean()

39.88

In [13]:
orneklem2.mean()

39.12

# BETİMSEL İSTATİSTİK

In [2]:
import seaborn as sns
tips = sns.load_dataset("tips")
df = tips.copy()
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [3]:
df.describe().T

count       mean       std   min      25%     50%      75%    max
total_bill  244.0  19.785943  8.902412  3.07  13.3475  17.795  24.1275  50.81
tip         244.0   2.998279  1.383638  1.00   2.0000   2.900   3.5625  10.00
size        244.0   2.569672  0.951100  1.00   2.0000   2.000   3.0000   6.00

In [4]:
!pip install researchpy
import researchpy as rp

In [5]:
rp.summary_cont(df[["total_bill","tip","size"]])

Variable      N     Mean      SD      SE  95% Conf.  Interval
0  total_bill  244.0  19.7859  8.9024  0.5699    18.6633   20.9086
1         tip  244.0   2.9983  1.3836  0.0886     2.8238    3.1728
2        size  244.0   2.5697  0.9511  0.0609     2.4497    2.6896

In [6]:
rp.summary_cat(df[["sex","smoker","day"]])

Variable Outcome  Count  Percent
0      sex    Male    157    64.34
1           Female     87    35.66
2   smoker      No    151    61.89
3              Yes     93    38.11
4      day     Sat     87    35.66
5              Sun     76    31.15
6             Thur     62    25.41
7              Fri     19     7.79

In [7]:
df[["tip","total_bill"]].cov()

tip  total_bill
tip         1.914455    8.323502
total_bill  8.323502   79.252939

In [8]:
df[["tip","total_bill"]].corr()

tip  total_bill
tip         1.000000    0.675734
total_bill  0.675734    1.000000